# Generated by Django 3.0 on 2023-11-24 09:05

from django.db import migrations
from oc_lettings_site.models import Profile as OldP
from profiles.models import Profile as NewP

def migrate_data(apps, schema_editor):
    for old_data in OldP.objects.all():
        NewP.objects.create(
            user=old_data.user,
            favorite_city=old_data.favorite_city
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231115_2321'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
