version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6



jobs:
  lint: # Ajout du job de linting
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: ruff check .
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.12.0


    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Collect static
          command: python manage.py collectstatic --noinput
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build-and-push-docker-image:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: setup
          command: |
            python -m venv venv &&
            source venv/bin/activate &&
            pip install -r requirements.txt    


  deploy: # this can be any name you choose
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to Heroku
          command: |
            
            $env:HEROKU_API_KEY=$HEROKU_TOKEN
            heroku config:set SECRET_KEY=$env:SECRET_KEY -a $env:HEROKU_APP_NAME
            heroku config:set DSN=$env:DSN -a $env:HEROKU_APP_NAME
            heroku container:login
            heroku container:push -a $env:HEROKU_APP_NAME web
            heroku container:release -a $env:HEROKU_APP_NAME web

workflows:
  test_my_app:
    jobs:
      - lint
      - build_and_test
      - deploy
             
              
              
#job de linting avant les tests
#ruff a la place de flake8
