# Generated by Django 3.0 on 2023-11-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0002_auto_20231124_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresses'},
        ),
    ]
