# Generated by Django 5.0 on 2024-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0003_auto_20231130_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
